name: i18n_gen
description: A sample command-line application with basic argument parsing.
version: 0.0.1
repository: https://github.com/liplum/i18n_gen

environment:
  sdk: ^3.6.2

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
